######################################################################
# Automatically generated by qmake (2.01a) ? 12 21 00:50:08 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

CONFIG(debug, debug|release){
	CONFIG += qt debug
	CONFIG += console
}
else{
}

# Input
HEADERS += switchitemview.h
FORMS += switchitemview.ui
SOURCES += main.cpp switchitemview.cpp
